{% set name = "stduuid" %}
{% set version = "1.2.2" %}
{% set sha256 = "3c88be0e696b64150c4de7a70f9f09c00a335186b0b0b409771ef9f56bca7d9a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mariusbancila/stduuid/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - gsl-lite
  run:
    - gsl-lite

test:
  commands:
    - test -f ${PREFIX}/include/uuid.h  # [unix]
    - test -f ${PREFIX}/share/cmake/stduuid/stduuid-config.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/stduuid/stduuid-version.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\uuid.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\stduuid\stduuid-config.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\stduuid\stduuid-version.cmake (exit 1)  # [win]

about:
  home: https://github.com/stduuid-stack/stduuid
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A C++17 cross-platform single-header library implementation for universally unique identifiers.
  description: A C++17 cross-platform single-header library implementation for universally unique identifiers.
  doc_url: https://github.com/mariusbancila/stduuid/blob/master/README.md
  dev_url: https://github.com/mariusbancila/stduuid/

extra:
  recipe-maintainers:
    - JohanMabille
    - Klaim
    
